ProjectSEO/Models/ProductAdd.cs
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjectSEO.Models
{
    public class ProductAdd
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public IFormFile ImageURL { get; set; }
        public int Stock { get; set; }
        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }

    }
}

ProjectSEO/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectSEO.Controllers
{
    public class CategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetCategoryList()
        {
            var categoryvalues = cm.GetList();
            return View(categoryvalues);
        }
    }
}

ProjectSEO/Controllers/CombineController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectSEO.Controllers
{
    public class CombineController : Controller
    {
        CombineManager cm = new CombineManager(new EfCombineDal());

        public ActionResult ContentByCombine(int combineId)
        {
            var combineValues = cm.GetList().Where(a => a.CombineID == combineId).ToList();
            return View(combineValues);
        }

        public ActionResult ContentByCombinee(int id)
        {
            var contentValues = cm.GetByID(id);
            return View(contentValues);
        }
    }
}

ProjectSEO/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectSEO.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            //Response.Status = "301 Kalıcı Yönlendirme";
            //Response.StatusCode = 301;
            //Response.StatusDescription = "Kalıcı Yönlendirme";
            //Response.AddHeader("Location", "www.?.com");
            //Response.End();

            return View();
        }
    }
}

ProjectSEO/Controllers/ProductController.cs
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using ProjectSEO.Models;
using Excel = Microsoft.Office.Interop.Excel;

namespace ProjectSEO.Controllers
{
    public class ProductController : Controller
    {
        ProductManager pm = new ProductManager(new EfProductDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());

        public ActionResult Index(int categoryId)
        {
            var productValues = pm.GetList().Where(a => a.CategoryID == categoryId).ToList();
            return View(productValues);
        }

        [HttpGet]
        public ActionResult EditProduct(int id)
        {
            List<SelectListItem> valueCategory = (from x in cm.GetList() select new SelectListItem { Text = x.CategoryName, Value = x.CategoryID.ToString() }).ToList();
            ViewBag.vlc = valueCategory;
            var productValue = pm.GetByID(id);
            return View(productValue);
        }

        [HttpPost]
        public ActionResult EditProduct(Product p)
        {
            pm.ProductUpdate(p);
            return RedirectToAction("Index", new { categoryId = p.CategoryID });
        }

        DbSEO c = new DbSEO();
        public ActionResult GetAllProduct(string p)
        {
            var values = from x in c.Products select x;
            if (!string.IsNullOrEmpty(p))
            {
                values = values.Where(y => y.ProductName.Contains(p));
            }
            return View(values.ToList());
        }

        [HttpGet]
        public ActionResult AddProduct(Product p)
        {
            List<SelectListItem> valueCategory = (from x in cm.GetList() select new SelectListItem { Text = x.CategoryName, Value = x.CategoryID.ToString() }).ToList();
            ViewBag.vlc = valueCategory;
            return View();
        }

        [HttpPost]
        public ActionResult AddProduct(ProductAdd p)
        {
            Product f = new Product();
            if (p.ImageURL != null)
            {
                var extension = Path.GetExtension(p.ImageURL.FileName);
                var newimagename = Guid.NewGuid() + extension;
                var location = Path.Combine(Directory.GetCurrentDirectory(), "ProjectSEO/images/", newimagename);
                var stream = new FileStream(location, FileMode.Create);
                p.ImageURL.CopyTo(stream);
                f.ProductImage = newimagename;
            }
            f.ProductName = p.Name;
            f.ProductPrice = p.Price;
            f.ProductQuantity = p.Stock;
            f.ProductComment = p.Description;
            f.CategoryID = p.CategoryId;
            pm.ProductAdd(f);
            return RedirectToAction("Index");
        }

        public ActionResult GetProducts(string key)
        {
            var test = pm.GetList();
            var products = pm.GetList().Where(a => a.ProductKey == key || a.ProductName.Contains(key)).ToList();
            return View(products);
        }

        [Route("Product/ContentByProduct/{id}/{name}/{key}")]
        public ActionResult ContentByProduct(int id)
        {
            var contentValues = pm.GetListByProductID(id);
            return View(contentValues);
        }

        [HttpGet]
        public ActionResult UploadExcel()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadExcel(HttpPostedFileBase excelFile)
        {
            if (excelFile == null
            || excelFile.ContentLength == 0)
            {
                ViewBag.Error = "Lütfen dosya seçimi yapınız.";
                return View();
            }
            else
            {
                if (excelFile.FileName.EndsWith("xls")
                || excelFile.FileName.EndsWith("xlsx"))
                {
                    string path = Server.MapPath("~/Content/" + excelFile.FileName);
                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }

                    excelFile.SaveAs(path);
                    Excel.Application application = new Excel.Application();
                    Excel.Workbook workbook = application.Workbooks.Open(path);
                    Excel.Worksheet worksheet = workbook.ActiveSheet;
                    Excel.Range range = worksheet.UsedRange;

                    List<Product> localList = new List<Product>();

                    for (int i = 2; i <= range.Rows.Count; i++)
                    {
                        Product lm = new Product();
                        lm.ProductID = Convert.ToInt32(((Excel.Range)range.Cells[i, 1]).Text);
                        lm.ProductName = ((Excel.Range)range.Cells[i, 2]).Text;
                        lm.ProductComment = ((Excel.Range)range.Cells[i, 3]).Text;
                        lm.ProductKey = ((Excel.Range)range.Cells[i, 4]).Text;
                        localList.Add(lm);
                    }

                    application.Quit();
                    ViewBag.Model = localList;
                    return View("ListExcel");
                }
                else
                {
                    return View();
                }
            }

        }
    }
}

ProjectSEO/Views/Combine/ContentByCombine.cshtml
@using EntityLayer.Concrete
@model List<Combine>

@{
    ViewBag.Title = "ContentByCombine";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<html>
<body class="hold-transition sidebar-mini">
    <!-- /.navbar -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Sana Özel Kombin</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    @foreach (var item in Model)
                    {
                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                            <div class="card bg-light">
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7">
                                            <h2 class="lead"><b>@item.CombineName</b></h2>
                                            <p class="text-muted text-sm">@item.CombineDescription </p>
                                            <!--<ul class="ml-4 mb-0 fa-ul text-muted">-->
                                                @*<a href="@Url.Action("GetProducts", "Product", new { key = item.ProductKey })" class="btn btn-sm btn-outline-danger">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-key"></i></span> @item.ProductKey</li>
                                                </a>*@
                                            <!--</ul>-->
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-credit-card"></i></span> Fiyat: @item.CombinePrice tl</li>
                                            </ul>
                                            @*<ul class="ml-4 mb-0 fa-ul text-muted">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-hourglass"></i></span> Stok: @item.ProductQuantity adet kaldı!</li>
                                            </ul>*@
                                        </div>
                                        <div class="col-5 text-center">
                                            <img alt="" class="img-circle img-fluid" @item.CombineImage>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="text-right">
                                        <a href="/Product/ProductAdd/@item.ProductID" class="btn btn-sm btn-primary">
                                            <i class="fas fa-shopping-cart"> Sepete Ekle</i>
                                        </a>
                                        @*<a href="@Url.Action("Index", "Product", new { combineId = 1 })" class="btn btn-sm btn-primary">
                                            <i class="fas fa-shopping-cart"> Sana Özel Kombin Ürünlerini Gör :)</i>
                                        </a>*@
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
</body>
</html>

ProjectSEO/Views/Product/AddProduct.cshtml
@model ProjectSEO.Models.ProductAdd

@{
    ViewBag.Title = "AddProduct";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Ürün Ekle</h2>
<br />
<form class="form-group" action="AddProduct" asp-controller="Product" method="post" enctype="multipart/form-data">
    <div class="form-group">
        @Html.Label("Ürün İsmi")
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        <br />
        @Html.Label("Ürün Açıklama")
        @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
        <br />
        @*@Html.Label("Ürün Anahtar Kelime")
        @Html.TextBoxFor(x => x., new { @class = "form-control" })
        <br />*@
        @Html.Label("Ürün Fiyat")
        @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
        <br />
        @Html.Label("Ürün Stok")
        @Html.TextBoxFor(x => x.Stock, new { @class = "form-control" })
        <br />
        @Html.Label("Ürün Görsel")
        @Html.TextBoxFor(x => x.ImageURL, new { @class = "form-control", @type = "file"})
        @*<input type="file" name="ImageURL"/>*@
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br />
        <button class="btn btn-info">Yeni Ürün Ekle</button>
    </div>
</form>

ProjectSEO/Views/Product/ContentByProduct.cshtml
@using EntityLayer.Concrete
@model List<Product>

@{
    ViewBag.Title = "ContentByProduct";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!--<html>
<body class="hold-transition sidebar-mini">-->
<!-- /.navbar -->
<!-- Content Header (Page header) -->
<!--<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Ürünler</h1>
            </div>
        </div>
    </div>-->
<!-- /.container-fluid -->
<!--</section>-->
<!-- Main content -->
<!--<section class="content">-->
<!-- Default box -->
<!--<div class="card card-solid">
    <div class="card-body pb-0">
        <div class="row d-flex align-items-stretch">
            @foreach (var item in Model)
            {
                <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                    <div class="card bg-light">
                        <div class="card-body pt-0">
                            <div class="row">
                                <div class="col-7">
                                    <h2 class="lead"><b>@item.ProductName</b></h2>
                                    <p class="text-muted text-sm">@item.ProductComment </p>
                                    <ul class="ml-4 mb-0 fa-ul text-muted">
                                        <a href="@Url.Action("GetProducts", "Product", new { key = item.ProductKey })" class="btn btn-sm btn-outline-danger">
                                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-key"></i></span> @item.ProductKey</li>
                                        </a>
                                    </ul>
                                    <ul class="ml-4 mb-0 fa-ul text-muted">
                                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-credit-card"></i></span> Fiyat: @item.ProductPrice tl</li>
                                    </ul>
                                    <ul class="ml-4 mb-0 fa-ul text-muted">
                                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-hourglass"></i></span> Stok: @item.ProductQuantity adet kaldı!</li>
                                    </ul>
                                </div>
                                <div class="col-5 text-center">
                                    <img alt="" class="img-circle img-fluid" @item.ProductImage>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="text-right">
                                <a href="/Product/EditProduct/@item.ProductID" class="btn btn-sm bg-teal">
                                    <i class="fas fa-plus"> Ürün Güncelle</i>
                                </a>
                                <a href="/Product/ProductAdd/@item.ProductID" class="btn btn-sm btn-primary">
                                    <i class="fas fa-shopping-cart"> Sepete Ekle</i>
                                </a>
                                <br />
                                <a href="@Url.Action("ContentByCombine", "Combine", new { combineId = 1 })" class="btn btn-sm btn-warning">
                                    <i class="fas fa-shopping-cart"> Sana Özel Kombin Ürünlerini Gör :)</i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>-->
<!-- /.card -->
<!--</section>-->
<!-- /.content -->
<!--</body>
</html>-->

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        
            
                
            <div class="col-sm-6">
                <h1>Ürün</h1>
            </div>
          

            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="card card-solid">
                    @foreach (var item in Model)
                    {
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12 col-sm-6">
                                    <h3 class="d-inline-block d-sm-none"></h3>
                                    <div class="col-12">
                                        <img alt="" class="img-circle img-fluid" @item.ProductImage>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <h3 class="my-3">@item.ProductName</h3>
                                    <p>@item.ProductComment</p>

                                    <ul class="ml-4 mb-0 fa-ul text-muted">
                                        <a href="@Url.Action("GetProducts", "Product", new { key = item.ProductKey })" class="btn btn-sm btn-outline-danger">
                                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-key"></i></span> @item.ProductKey</li>
                                        </a>
                                    </ul>

                                    <div class="bg-gray py-2 px-3 mt-4">
                                        <h5 class="mb-0">
                                            Fiyat: @item.ProductPrice tl
                                        </h5>
                                    </div>
                                    <div class="bg-cyan py-2 px-3 mt-4">
                                        <h5 class="mb-0">
                                                Stok: Acele et. Bu üründen sadece @item.ProductQuantity tane kaldı!
                                        </h5>
                                    </div>
                                        <div class="card-footer">
                                            <div class="text-right">
                                                <a href="/Product/EditProduct/@item.ProductID" class="btn btn-sm bg-teal">
                                                    <i class="fas fa-plus"> Ürün Güncelle</i>
                                                </a>
                                                <a href="/Product/ProductAdd/@item.ProductID" class="btn btn-sm btn-primary">
                                                    <i class="fas fa-shopping-cart"> Sepete Ekle</i>
                                                </a>
                                                <br />
                                                <a href="@Url.Action("ContentByCombine", "Combine", new { combineId = 1 })" class="btn btn-sm btn-warning">
                                                    <i class="fas fa-shopping-basket"> Sana Özel Kombin Ürünlerini Gör :)</i>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                        </div>
                    }
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </section>
        <!-- /.content-wrapper -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
</body>
</html>

ProjectSEO/Views/Product/EditProduct.cshtml
@model EntityLayer.Concrete.Product

@{
    ViewBag.Title = "EditProduct";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Ürün Güncelle</h2>
@using (Html.BeginForm("EditProduct", "Product", FormMethod.Post))
{
    @Html.HiddenFor(x => x.ProductID)
    <div class="form-group">
        @Html.Label("Ürün İsmi")
        @Html.TextBoxFor(x => x.ProductName, new { @class = "form-control" })
        <br />
        @Html.Label("Ürün Açıklama")
        @Html.TextBoxFor(x => x.ProductComment, new { @class = "form-control" })
        <br />
        @Html.Label("Ürün Anahtar Kelime")
        @Html.TextBoxFor(x => x.ProductKey, new { @class = "form-control" })
        <br />
        @Html.Label("Ürün Fiyat")
        @Html.TextBoxFor(x => x.ProductPrice, new { @class = "form-control" })
        <br />
        @Html.Label("Ürün Stok")
        @Html.TextBoxFor(x => x.ProductQuantity, new { @class = "form-control" })
        <br />
        @Html.Label("Ürün Görsel")
        @Html.TextBoxFor(x => x.ProductImage, new { @class = "form-control" })
        <br />
        @Html.Label("Category Name")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

ProjectSEO/Views/Product/GetAllProduct.cshtml
@using EntityLayer.Concrete
@model List<Product>

@{
    ViewBag.Title = "GetAllProduct";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<html>
<body class="hold-transition sidebar-mini">
    <!-- /.navbar -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Ürünler</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    @using (Html.BeginForm("GetAllProduct", "Product", FormMethod.Post))
                    {
                        <p>
                            Aranacak Kelimeyi Giriniz: @Html.TextBox("p")
                            <input type="submit" value="Ara" />
                        </p>
                    }
                </div>
            </div>
        </div>
        <!-- /.card -->
    </section>
    <section class="content">
        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    @foreach (var item in Model)
                    {
                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                            <div class="card bg-light">
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7">
                                            <h2 class="lead"><b>@item.ProductName</b></h2>
                                            <p class="text-muted text-sm">@item.ProductComment </p>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <a href="@Url.Action("GetProducts", "Product", new { key = item.ProductKey })" class="btn btn-sm btn-outline-danger">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-key"></i></span> @item.ProductKey</li>
                                                </a>
                                            </ul>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-credit-card"></i></span> Fiyat: @item.ProductPrice tl</li>
                                            </ul>
                                        </div>
                                        <div class="col-5 text-center">
                                            <img alt="" class="img-circle img-fluid" @item.ProductImage>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="text-right">
                                        <a href="/Product/EditProduct/@item.ProductID" class="btn btn-sm bg-teal">
                                            <i class="fas fa-comments"> Ürün Güncelle</i>
                                        </a>
                                        <a href="/Product/ContentByProduct/@item.ProductID/@item.ProductName/@item.ProductKey" class="btn btn-sm btn-light">
                                            <i class="fas fa-star"> Ürünü İncele</i>
                                        </a>
                                        <a href="/Product/ProductAdd/@item.ProductID" class="btn btn-sm btn-primary">
                                            <i class="fas fa-shopping-cart"> Sepete Ekle</i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
</body>
</html>

ProjectSEO/Views/Product/Index.cshtml
@using EntityLayer.Concrete
@model List<Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<html>
<body class="hold-transition sidebar-mini">
    <!-- /.navbar -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Ürünler</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    @foreach (var item in Model)
                    {
                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                            <div class="card bg-light">
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7">
                                            <h2 class="lead"><b>@item.ProductName</b></h2>
                                            <p class="text-muted text-sm">@item.ProductComment </p>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <a href="@Url.Action("GetProducts", "Product", new { key = item.ProductKey })" class="btn btn-sm btn-outline-danger">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-key"></i></span> @item.ProductKey</li>
                                                </a>
                                            </ul>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-credit-card"></i></span> Fiyat: @item.ProductPrice tl</li>
                                            </ul>
                                        </div>
                                        <div class="col-5 text-center">
                                            <img alt="" class="img-circle img-fluid" @item.ProductImage>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="text-right">
                                        <a href="/Product/EditProduct/@item.ProductID" class="btn btn-sm bg-teal">
                                            <i class="fas fa-plus"> Ürün Güncelle</i>
                                        </a>
                                        <a href="/Product/ContentByProduct/@item.ProductID/@item.ProductName/@item.ProductKey" class="btn btn-sm btn-light">
                                            <i class="fas fa-star"> Ürünü İncele</i>
                                        </a>
                                        <a href="/Product/ProductAdd/@item.ProductID" class="btn btn-sm btn-primary">
                                            <i class="fas fa-shopping-cart"> Sepete Ekle</i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
</body>
</html>
<a href="/Product/AddProduct" class="btn btn-primary">Yeni Ürün Ekle</a>
<a href="/Product/UploadExcel" class="btn btn-primary">Excel'den Ürün Ekle</a>

ProjectSEO/Views/Product/UploadExcel.cshtml
@{
    ViewBag.Title = "UploadExcel";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("UploadExcel", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr>
            <td>Eklenecek Dosya</td>
            <td>
                <input type="file" name="excelFile" />
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" name="Submit" value="Submit" />
            </td>
        </tr>
    </table>
}